version: "3.4"

services:
  quizapi:
    image: quizapi
    build:
      context: .
      dockerfile: src/Quiz.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5075:5075
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DatabaseConnection=Host=postgres;Port=5432;Username=postgres;Password=postgres;Database=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
